export const ICON_INFO = 'ep:info-filled'
export const ICON_LOADING_DOTS = 'eos-icons:three-dots-loading'
export const ICON_LOADING_CIRCLE = 'line-md:loading-twotone-loop'
export const ICON_EMPTY = 'tabler:table-alias'
export const ICON_ERROR_LOAD = 'icon-park-outline:database-fail'
